dataset: europarl_de-en_train (8)
checkpoint: 2eu_10tt_1eu_5tt_5nc_1eu_5tt

upper_bounds: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
batch_size: 256
sort_by_loss_desc: true

decode_from_loss: 2.5
use_bf16: true